const Treatment = require('../models/Treatment');
const Condition = require('../models/Condition');
const { createSystemNotification } = require('./notificationController');

// ── Helpers ────────────────────────────────────────────────────────────────
const verifyOwnership = (treatment, user) => {
  if (user.role === 'admin' || user.role === 'doctor') return true;
  return treatment.patientId.toString() === user._id.toString();
};

const formatTreatment = (t) => ({
  id: t._id,
  patientId: t.patientId?._id || t.patientId,
  doctorId: t.doctorId?._id || t.doctorId,
  doctorName: t.doctorId?.name || null,
  isVerified: t.isVerified,
  condition: t.condition,
  severity: t.severity,
  symptoms: t.symptoms,
  recommendations: t.recommendations,
  medications: t.medications,
  warnings: t.warnings,
  emergencyWarnings: t.emergencyWarnings,
  createdAt: t.createdAt,
  updatedAt: t.updatedAt
});

// ── POST /api/treatments ───────────────────────────────────────────────────
// Usually generated by ML, but can be manually generated
exports.createTreatment = async (req, res, next) => {
  try {
    const {
      patientId, condition, conditionId, confidence, severity,
      symptoms, medications, recommendations, lifestyle, warnings,
      emergencyWarnings, doctorConsultationRecommended, followUpSchedule
    } = req.body;

    const treatment = await Treatment.create({
      patientId,
      condition,
      conditionId,
      confidence,
      severity,
      symptoms,
      medications,
      recommendations,
      lifestyle,
      warnings,
      emergencyWarnings,
      doctorConsultationRecommended,
      followUpSchedule,
      isVerified: false,
      doctorId: null
    });

    res.status(201).json({
      success: true,
      message: 'Treatment recommendation created successfully',
      data: treatment
    });
  } catch (error) {
    next(error);
  }
};

// ── GET /api/treatments/patient/:patientId ─────────────────────────────────
exports.getPatientTreatments = async (req, res, next) => {
  try {
    const { patientId } = req.params;

    if (req.user.role === 'patient' && patientId !== req.user._id.toString()) {
      return res.status(403).json({ success: false, error: 'Access denied' });
    }

    const treatments = await Treatment.find({ patientId })
      .populate('conditionId', 'name description')
      .populate('doctorId', 'name email')
      .sort({ createdAt: -1 });

    res.status(200).json({
      success: true,
      data: treatments.map(formatTreatment)
    });
  } catch (error) {
    next(error);
  }
};

// ── GET /api/treatments/:id ────────────────────────────────────────────────
exports.getTreatment = async (req, res, next) => {
  try {
    const { id } = req.params;

    const treatment = await Treatment.findById(id)
      .populate('conditionId', 'name description symptoms')
      .populate('patientId', 'name email')
      .populate('doctorId', 'name email');

    if (!treatment) {
      return res.status(404).json({ success: false, error: 'Treatment not found' });
    }

    if (!verifyOwnership(treatment, req.user)) {
      return res.status(403).json({ success: false, error: 'Access denied' });
    }

    res.status(200).json({
      success: true,
      data: formatTreatment(treatment)
    });
  } catch (error) {
    next(error);
  }
};

// ── PATCH /api/treatments/:id/verify ───────────────────────────────────────
// Doctor verifies the ML output
exports.verifyTreatment = async (req, res, next) => {
  try {
    const { id } = req.params;

    const treatment = await Treatment.findById(id);
    if (!treatment) {
      return res.status(404).json({ success: false, error: 'Treatment not found' });
    }

    // Attach doctor ID and verify
    treatment.isVerified = true;
    treatment.doctorId = req.user._id;
    treatment.updatedAt = Date.now();
    
    await treatment.save();
    
    // fetch populated for response
    const populated = await Treatment.findById(id).populate('doctorId', 'name email');

    // Notify patient of doctor verification
    await createSystemNotification({
      userId: treatment.patientId,
      type: 'alert',
      title: 'Treatment Plan Verified',
      message: `Your AI-generated treatment plan has been verified by Dr. ${populated.doctorId.name}.`,
      actionUrl: `/patient/treatments/${id}`
    });

    res.status(200).json({
      success: true,
      message: 'Treatment successfully verified by doctor',
      data: formatTreatment(populated)
    });
  } catch (error) {
    next(error);
  }
};

// ── PATCH /api/treatments/:id ──────────────────────────────────────────────
exports.updateTreatment = async (req, res, next) => {
  try {
    const { id } = req.params;
    const updateData = req.body;

    const existing = await Treatment.findById(id);
    if (!existing) {
      return res.status(404).json({ success: false, error: 'Treatment not found' });
    }

    const treatment = await Treatment.findByIdAndUpdate(
      id,
      { ...updateData, updatedAt: Date.now() },
      { new: true, runValidators: true }
    ).populate('doctorId', 'name email');

    res.status(200).json({
      success: true,
      data: formatTreatment(treatment)
    });
  } catch (error) {
    next(error);
  }
};

// ── DELETE /api/treatments/:id ─────────────────────────────────────────────
exports.deleteTreatment = async (req, res, next) => {
  try {
    const { id } = req.params;
    const treatment = await Treatment.findById(id);
    if (!treatment) {
      return res.status(404).json({ success: false, error: 'Treatment not found' });
    }

    await Treatment.findByIdAndDelete(id);

    res.status(200).json({
      success: true,
      message: 'Treatment deleted successfully'
    });
  } catch (error) {
    next(error);
  }
};

// ── GET /api/treatments/condition/:conditionId ─────────────────────────────
exports.getTreatmentsByCondition = async (req, res, next) => {
  try {
    const { conditionId } = req.params;
    const treatments = await Treatment.find({ conditionId })
      .populate('conditionId', 'name description')
      .populate('doctorId', 'name email')
      .sort({ confidence: -1 });

    res.status(200).json({
      success: true,
      data: treatments.map(formatTreatment)
    });
  } catch (error) {
    next(error);
  }
};